spring:
  application:
    name: api-gateway
server:
  port: 7006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

zuul:
  routes:
    eureka-client:
      path: /eureka-client-consumer/**               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      service-id: eureka-client-consumer             # 想要映射到的路径 系统管理服务